name: rsocial2
description: A new Flutter application.

# The following defines the version and build number for your application.v
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+30

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  better_player:  ^0.0.65
  cupertino_icons: ^1.0.2
  page_transition: 1.1.7+2
  font_awesome_flutter:
  flutter_linkify: ^5.0.0
  #flutter_native_admob: ^2.1.0+3
  flutter_svg: ^0.19.3
  #0.19.0
  image_picker: ^0.7.4
  flutter_swiper:
  search_widget: ^1.0.2
  url_launcher:
  firebase_remote_config:
  firebase_core:
  google_sign_in: ^4.0.1+1
  cloud_firestore: ^1.0.6
  firebase_auth: ^1.1.2
  flutter_facebook_login:
  animated_text_kit: 2.4.1
  intl_phone_field: ^1.3.0
  http: ^0.13.1
  firebase_analytics: ^5.0.11
  modal_progress_hud: ^0.1.3
  permission_handler: ^7.0.0
  share: ^2.0.1
  package_info:
  firebase_dynamic_links:
  shared_preferences: ^2.0.5
  firebase_messaging: ^9.1.2
  image_cropper: ^1.3.0
  path_provider:
  image: ^2.0.7
  uuid: ^2.0.0
  sembast:
  timeago: ^2.0.29
  fluttertoast:
  overlay_support:
  animated_splash_screen:
  flutter_app_badger: ^1.1.2
  provider:
  webview_flutter: ^2.0.2
  #chewie: ^1.0.0
  video_player: ^2.1.1
  photo_view: ^0.11.1
  #meet_network_image: 
  cached_network_image:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "android/app/src/main/res/drawable/logo3.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - assets/
  fonts:

    - family: CinzelDecorative
      fonts:
        - asset: fonts/CinzelDecorative-Regular.ttf
        - asset: fonts/CinzelDecorative-Bold.ttf
        - asset: fonts/CinzelDecorative-Black.ttf

    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf

    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Montserrat
      fonts:
       - asset: fonts/Montserrat-SemiBold.ttf

    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
